# Generated by Django 4.1.1 on 2022-10-03 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_quiz.studentclass')),
            ],
        ),
    ]
