# Generated by Django 4.1.1 on 2022-10-02 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_quiz', '0007_remove_classtest_test_score_classtest_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtest',
            name='student',
        ),
        migrations.RemoveField(
            model_name='classtest',
            name='score',
        ),
        migrations.AddField(
            model_name='classtest',
            name='score',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
