# Generated by Django 4.1.1 on 2022-10-02 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_quiz', '0008_remove_classtest_student_remove_classtest_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtest',
            name='score',
        ),
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='classtest',
            name='scores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_quiz.studentscore'),
        ),
    ]
