# Generated by Django 4.1.1 on 2022-10-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_quiz', '0009_remove_classtest_score_studentscore_classtest_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtest',
            name='scores',
        ),
        migrations.AddField(
            model_name='classtest',
            name='scores',
            field=models.ManyToManyField(to='school_quiz.studentscore'),
        ),
    ]
