# Generated by Django 4.1.1 on 2022-10-02 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_quiz', '0010_remove_classtest_scores_classtest_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtest',
            name='scores',
        ),
        migrations.AddField(
            model_name='studentscore',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_quiz.classtest'),
        ),
    ]
